language: node_js
node_js:
  - '6'
notifications:
  slack:
    secure: xgKJhyZ6IHMkKH5p7ZiOY2zd6d0tMAIhGhBxwRb3zgJMnoSNdxYOR6/rveAJ4s/ZPqidUC1g8AjnhY2F8a0yt82+6rZf/cfeIZPvm9zKztNhEJ/YKme4sBomR6ElaWf90zYHAXXswypmz/zpipA1WxzAor8Sq8xcGPBrAMHRGwRnrDwLMZYz/j2uU32k17tcm7Cb3TliRiwEMT7avl0aDnEId8oA0dvU6dhak5J980tPbvjm8/gFXM62DoDUY0jxQqCGL7ypJnXo6nBMErJo3j+VPvieGSWtDTiqAOuoFxd5Xdw0cGTmS3igKZBIGDTnj84qaWoxadawg32Z2rrG2OjoCyVrLBRMsqm+R2rmdhTULZ8Ya4ReELjBBKD6gvkqAEKEvwSuMlPAVxjaFO2sA+tDbPnUngP0V/6nEBHjNb9het/aYSY/kw2OSgLHLGI0h48pieTQlZfr5MYcv6nsUPzQ4mvMRciJrHpsw7MqFcXtrFqcVjB7vqEp6UKfReqEviVVZQlD7J0Ztc75fsZoc2ZwJLketgoYVB8svoQ/cu+KUuNMKZvBtaxpdibNtl1cgBquKmnUSfSwsSOGH3M5IohM8DWuOc7Lnq2m2mC8TSoY7Q+uhshIAM5GidE0rFI6LNeWYit24ahlzBDPRoLyRx9NnGkg/iz6ruA9YIJTzhM=
