language: node_js
node_js:
    - node
    - lts/*
notifications:
  slack:
    secure: nryzT5JNGAD6vkiNTa2iJfCswSJxT6BdpEILDVxfvRAWrvEcm2X0dhgRx/GNVX1xe9Nko6/r2t3qAU1btA6AZhh0QXGs5rnHDB8KzUTgnL+Vw4MZRwbvtwl5XCRjTinajIoiheFdhYOhBFrexmAXOVfjDN+GDBBFrra6eoLrFnIhoUeIJtvtq8xJy2jO9vykx7rJklWwXZkLp7f4XlQl/lCCHTyvOwUbthPl2m5py1ytM586Tves3LBTpsxUC45ZcDssh9uCRQ11vBZx1GlBjxFxpjcTsfBaGtFWXxjTFushr3ThyhY8SdhcX5gpMqKzBIrf+vtXPCGmmTjtdA3hFbBgQPPgVUJDRPts8HTqU2HmK56ow76i4xYCcJKStIzumDz9kVC1+ST+81qwZHcDfDb02reoemB6MAd4Hkpb555+xZKQLyTF6en85VYjDGx41mQQIF7BFWkXniJk8Pzsc7eRcyvpxYHMZLVnoiMNb5jaiJLpwxZZldtmVg5/W7GXo3AiqtyJw8MkXrMZcvlLpJ9Rm2JwRhmrtf1YQq1ARdweHwq4uWITH79vRHX7gVYh+PEv5mGTWnoA0nOKDG/j1QyZ+4vA7kjbO2n9NzJkYRY/d/WSiPBjVzMnER1m0wUhEESktF7AFsJbdIyAk6BJVvCOi3wW9msWf4ZfOvWkFyQ=
